x-logging: &logging
  options:
    max-size: "256k"
    max-file: "1"
  driver: json-file

services:
  reverse-proxy:
    restart: always
    build:
      context: ./reverse-proxy
    ports:
      - "${LISTEN_IP}:${LISTEN_PORT}:80"
    environment:
      - UI_BASE_URI=$UI_BASE_URI
      - API_BASE_URI=$API_BASE_URI
    logging: *logging

  ui:
    build:
      context: ./ui
      network: host
      args:
        - BASE_URI=$UI_BASE_URI
    restart: always
    logging: *logging
    networks:
      default:
        ipv4_address: "${STATIC_SUBNET}.101"
    environment:
      - API_BASE_URI=$API_BASE_URI
      - LISTEN_PORT=$LISTEN_PORT
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public

  backend:
    build:
      context: ./backend
      network: host
    restart: always
    environment:
      - "LOG_LEVEL=INFO"
      - "API_BASE_URI=$API_BASE_URI"
      - "OPENAI_BASE_URL=$OPENAI_API_BASE"
      - "OPENAI_API_BASE=$OPENAI_API_BASE"
      - "OPENAI_API_KEY=$OPENAI_API_KEY"
      - "LLM_MODEL_BASE=$LLM_MODEL_BASE"
    logging: *logging
    networks:
      default:
        ipv4_address: "${STATIC_SUBNET}.102"
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5678:5678" # debugger
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${STATIC_SUBNET}.0/24"
          gateway: "${STATIC_SUBNET}.1"
